OpenShift:
  development:
    host: localhost
    database: RailsApp

  test:
    host: localhost
    database: RailsApp

  # set these environment variables on your prod server
  production:
    host: <%= ENV['OPENSHIFT_MONGODB_DB_HOST'] %>
    port: <%= ENV['OPENSHIFT_MONGODB_DB_PORT'] %>
    username: <%= ENV['OPENSHIFT_MONGODB_DB_USERNAME'] %>
    password: <%= ENV['OPENSHIFT_MONGODB_DB_PASSWORD'] %>
    database: <%= ENV['OPENSHIFT_MONGODB_DB_DATABASE'] %>
